/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KipuBank } from "./KipuBank";
export * as factories from "./factories";
export { KipuBank__factory } from "./factories/KipuBank__factory";
